name: picability
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.8.2
  google_sign_in: ^6.2.1
  flutter_slidable: ^3.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
