// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTfNlsotRCUK677Kha_sr2mB3KrzmioeA',
    appId: '1:541799415730:web:23b99064f05aff6b796eab',
    messagingSenderId: '541799415730',
    projectId: 'picability2-e94b7',
    authDomain: 'picability2-e94b7.firebaseapp.com',
    storageBucket: 'picability2-e94b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_24QcsMAe93InaKxoBNXhn9px-5BVZw',
    appId: '1:541799415730:android:ca55ad024b1fbe8a796eab',
    messagingSenderId: '541799415730',
    projectId: 'picability2-e94b7',
    storageBucket: 'picability2-e94b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ST28-omUAEl-y0vgFoa4w1TTuYgHutc',
    appId: '1:541799415730:ios:dcfffa7790e215c0796eab',
    messagingSenderId: '541799415730',
    projectId: 'picability2-e94b7',
    storageBucket: 'picability2-e94b7.appspot.com',
    iosBundleId: 'com.azicii.picability',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ST28-omUAEl-y0vgFoa4w1TTuYgHutc',
    appId: '1:541799415730:ios:68ab42b096dd3e37796eab',
    messagingSenderId: '541799415730',
    projectId: 'picability2-e94b7',
    storageBucket: 'picability2-e94b7.appspot.com',
    iosBundleId: 'com.azicii.picability.RunnerTests',
  );
}
